### ISSUE TITLE
error

### ISSUE THREAD

**Issue by PMPBinZhang** [PD-Mera/Anime-Face-Detector-MM#1]
Hello, I got the error, ImportError: cannot import name 'inference_top_down_pose_model' from 'mmpose.apis' (/home/meta/miniconda3/envs/anime_kps/lib/p

**Comment by PD-Mera** [comment]
@PMPBinZhang Can you show me full log of the error?

**Comment by PD-Mera** [comment]
This bug cause by version change of mm libraries. I have fixed it. Feel free to open issue if anything happen
